[workspace]
resolver = "2"
members = [
    "fff",
    "cli",
    "api",
]

[workspace.dependencies]
spiceai = "2.0.0"
# arrow version needs to match spiceai dep
arrow = "51.0.0"
# arrow = { version = "51.0.0", features = ["prettyprint"] }
