name: Build and Publish Docker Images

on:
  push:
    branches:
      - main 

jobs:
  build-melange-api:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Melange API Image
        run: |
          docker build -t anowell/melange-api:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Melange API Image
        run: |
          docker push anowell/melange-api:latest

  build-melange-spice:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Melange Spice Image
        run: |
          docker build -t anowell/melange-spice:latest -f Dockerfile.spice .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Melange Spice Image
        run: |
          docker push anowell/melange-spice:latest

  build-melange-web:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Melange Web Image
        run: |
          docker build -t anowell/melange-web:latest web

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Melange Web Image
        run: |
          docker push anowell/melange-web:latest
